### ISSUE TITLE
Niewłaściwa kolejność elementów na stronie z płatnością przy pomocy karty

### ISSUE THREAD

**Issue by Ernold11** [PayU-EMEA/plugin_magento_2#40]
Na stronie do podawania danych karty w celu dokonania płatności przełączanie się przyciskiem tab między polami do wypełnienia przenosi z **_pola kodu CSV_** na przycisk **_zmień walutę_**.
Logiczniej by było gdyby od razu przenosiło do pola **_imię i nazwisko_**. 
Przez takie zachowanie trzeba wcisnąć o jeden raz więcej przycisk TAB na klawiaturze, jeżeli ktoś używa tej formy przejścia między polami zamiast klikania myszą.

**Comment by regdos** [comment]
Dziękujemy za informację. Nie jest to zachowanie pluginu tylko strony płatnościowej PayU ale wkrótce zostanie to poprawione.
