### ISSUE TITLE
current plugin is not supported with php 7.4 i.e magento 2.4

### ISSUE THREAD

**Issue by NTK-2016** [PayU-EMEA/plugin_magento_2#42]
![image](https://user-images.githubusercontent.com/24722367/114711114-322fc980-9d4c-11eb-9fe1-02f1985b181b.png)

Payu plugin is not supported with PHP 7.4 when i'm using composer, please update. I have tried with up manually download in app/code but this is not working ,in that case i have an issue in Transaction is declined error

**Comment by regdos** [comment]
@NTK-2016 For Magento 2.4 please use https://packagist.org/packages/payu/magento24-payment-gateway
